In [4]:
import seaborn as sns
df = sns.load_dataset("penguins")
df.shape
df["body_mass_g"] > 4000

0      False
1      False
2      False
3      False
4      False
       ...
339    False
340     True
341     True
342     True
343     True
Name: body_mass_g, Length: 344, dtype: bool

In [5]:
df[df["species"] == "Gentoo"]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
220,Gentoo,Biscoe,46.1,13.2,211.0,4500.0,Female
221,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,Male
222,Gentoo,Biscoe,48.7,14.1,210.0,4450.0,Female
223,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,Male
224,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,Male
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [6]:
df[(df["species"] == "Gentoo") & (df["body_mass_g"] > 5000)]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
221,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,Male
223,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,Male
224,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,Male
227,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,Male
229,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,Male
...,...,...,...,...,...,...,...
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,Male
337,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,Male
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

Now it only shows the Gentoo species with a bm above 5000 g. NEVER FORGET THE BRACKETS HERE.

In [7]:
df["body_mass_g"].isna().sum()

np.int64(2)

In [9]:
df_filtered = df[df["body_mass_g"] > 0]
len(df) - len(df_filtered)

2

Missing values get silently dropped by the filter because NaN values are not bigger than 0, so we should check if any penguins aren't assigned a body weight by using .isna